import type { ToolSpec } from "./types";

export const TIER1_TOOLS: Record<string, ToolSpec> = {
  "merge-pdf": {
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one file. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: true,
    kind: "merge",
  },
  "split-pdf": {
    slug: "split-pdf",
    title: "Split PDF",
    description: "Split a PDF into parts by page ranges. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "split",
  },
  "images-to-pdf": {
    slug: "images-to-pdf",
    title: "Images to PDF",
    description: "Convert JPG/PNG/WebP images into a single PDF locally.",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    acceptMime: ".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp",
    multiple: true,
    kind: "images-to-pdf",
  },
  "jpg-to-pdf": {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPEG images to PDF locally.",
    accepts: [".jpg", ".jpeg"],
    acceptMime: ".jpg,.jpeg,image/jpeg",
    multiple: true,
    kind: "images-to-pdf",
  },
  "png-to-pdf": {
    slug: "png-to-pdf",
    title: "PNG to PDF",
    description: "Convert PNG images to PDF locally.",
    accepts: [".png"],
    acceptMime: ".png,image/png",
    multiple: true,
    kind: "images-to-pdf",
  },
  "webp-to-pdf": {
    slug: "webp-to-pdf",
    title: "WebP to PDF",
    description: "Convert WebP images to PDF locally.",
    accepts: [".webp"],
    acceptMime: ".webp,image/webp",
    multiple: true,
    kind: "images-to-pdf",
  },
  "rotate-pdf": {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate pages by 90°, 180° or 270°. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "rotate",
  },
  "delete-pages": {
    slug: "delete-pages",
    title: "Delete Pages",
    description: "Remove pages from a PDF. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "delete-pages",
  },
  "extract-pages": {
    slug: "extract-pages",
    title: "Extract Pages",
    description: "Keep only selected pages as a new PDF. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "extract-pages",
  },
  "pdf-to-jpg": {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Export PDF pages as JPEG images. Rendered locally in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-image",
  },
  "pdf-to-png": {
    slug: "pdf-to-png",
    title: "PDF to PNG",
    description: "Export PDF pages as lossless PNG images. Rendered locally.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-image",
  },
  "pdf-to-webp": {
    slug: "pdf-to-webp",
    title: "PDF to WebP",
    description: "Export PDF pages as modern WebP images. Rendered locally.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-image",
  },
  "pdf-to-text": {
    slug: "pdf-to-text",
    title: "PDF to Text",
    description: "Extract raw text with reading order. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-text",
  },
  "pdf-to-json": {
    slug: "pdf-to-json",
    title: "PDF to JSON",
    description: "Extract per-page text as structured JSON. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-text",
  },
  "pdf-to-markdown": {
    slug: "pdf-to-markdown",
    title: "PDF to Markdown",
    description: "Extract text formatted as Markdown. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-text",
  },
  "add-watermark": {
    slug: "add-watermark",
    title: "Add Watermark",
    description: "Stamp diagonal text across pages. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "watermark",
  },
  "page-numbers": {
    slug: "page-numbers",
    title: "Page Numbers",
    description: "Stamp page numbers with a custom start. Runs fully in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "page-numbers",
  },
  "crop-pdf": {
    slug: "crop-pdf",
    title: "Crop PDF",
    description: "Trim page margins locally in your browser.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "crop",
  },
  "compress-pdf": {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Rewrite with object streams and strip metadata. 100% on-device.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "compress",
  },
  "bates-numbering": {
    slug: "bates-numbering",
    title: "Bates Numbering",
    description: "Stamp sequential litigation IDs (e.g. ACME-000123) on every page.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "bates",
  },
  "header-footer": {
    slug: "header-footer",
    title: "Header & Footer",
    description: "Running header plus footer with {p} page-number support.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "header-footer",
  },
  "add-stamps": {
    slug: "add-stamps",
    title: "Add Stamps",
    description: "Diagonal APPROVED / CONFIDENTIAL / DRAFT rubber-stamp overlay.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "stamp",
  },
  "table-of-contents": {
    slug: "table-of-contents",
    title: "Table of Contents",
    description: "Insert linked TOC pages with clickable jump-to-page entries.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "toc",
  },
  "sign-pdf": {
    slug: "sign-pdf",
    title: "Sign PDF",
    description: "Stamp a visual signature image or typed name. Not cryptographic.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "sign",
  },
  "pdf-form-filler": {
    slug: "pdf-form-filler",
    title: "PDF Form Filler",
    description: "Fill AcroForm text boxes, checkboxes and dropdowns locally.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "form-fill",
  },
  "svg-to-pdf": {
    slug: "svg-to-pdf",
    title: "SVG to PDF",
    description: "Rasterize vector SVG graphics into a PDF locally.",
    accepts: [".svg"],
    acceptMime: ".svg,image/svg+xml",
    multiple: false,
    kind: "svg-to-pdf",
  },
  "text-to-pdf": {
    slug: "text-to-pdf",
    title: "Text to PDF",
    description: "Paginated plain-text layout with word wrap.",
    accepts: [".txt"],
    acceptMime: ".txt,text/plain",
    multiple: false,
    kind: "text-to-pdf",
  },
  "markdown-to-pdf": {
    slug: "markdown-to-pdf",
    title: "Markdown to PDF",
    description: "Headings, lists, code blocks and quotes rendered to PDF.",
    accepts: [".md", ".markdown"],
    acceptMime: ".md,.markdown,text/markdown",
    multiple: false,
    kind: "markdown-to-pdf",
  },
  "csv-to-pdf": {
    slug: "csv-to-pdf",
    title: "CSV to PDF",
    description: "Delimited data laid out as a paginated table grid.",
    accepts: [".csv"],
    acceptMime: ".csv,text/csv",
    multiple: false,
    kind: "csv-to-pdf",
  },
  "pdf-to-word": {
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Extract text into an editable .docx (headings detected).",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-word",
  },
  "pdf-to-excel": {
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Detect table grids spatially and export one sheet per table.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-excel",
  },
  "extract-images": {
    slug: "extract-images",
    title: "Extract Images",
    description: "Pull embedded raster images out as PNG files.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "extract-images",
  },
  "edit-bookmarks": {
    slug: "edit-bookmarks",
    title: "Edit Bookmarks",
    description: "Read, reorder, rename, and rebuild the bookmark outline tree.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "bookmarks",
  },
  "word-to-pdf": {
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOCX paragraphs, headings, and tables to PDF.",
    accepts: [".docx"],
    acceptMime: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: false,
    kind: "word-to-pdf",
  },
  "excel-to-pdf": {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Render XLSX worksheets as bordered PDF tables.",
    accepts: [".xlsx"],
    acceptMime: ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    multiple: false,
    kind: "excel-to-pdf",
  },
  "pdf-to-csv": {
    slug: "pdf-to-csv",
    title: "PDF to CSV",
    description: "Heuristic table dump: lines to rows, gaps to columns.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "pdf-to-csv",
  },
  "duplicate-organize": {
    slug: "duplicate-organize",
    title: "Duplicate & Organize",
    description: 'Re-sequence pages by order spec ("3, 1-2, 1" duplicates too).',
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "duplicate",
  },
  "compare-pdfs": {
    slug: "compare-pdfs",
    title: "Compare PDFs",
    description: "Text-based diff: per-page similarity plus line changes.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: true,
    kind: "compare",
  },
  "fix-page-size": {
    slug: "fix-page-size",
    title: "Fix Page Size",
    description: "Standardize every page to A4 / Letter / Legal / A3.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "page-size",
  },
  "repair-pdf": {
    slug: "repair-pdf",
    title: "Repair PDF",
    description: "Structural rebuild (xref/trailer fix) via the qpdf engine.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "repair",
  },
  "rasterize-pdf": {
    slug: "rasterize-pdf",
    title: "Rasterize PDF",
    description: "Bake pages to bitmaps: text unselectable, vectors frozen.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "rasterize",
  },
  "deskew-pdf": {
    slug: "deskew-pdf",
    title: "Deskew PDF",
    description: "Auto-straighten slanted scans: detect tilt per page, rotate, rebuild.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "deskew",
  },
  "protect-pdf": {
    slug: "protect-pdf",
    title: "Protect PDF",
    description: "AES-256 password encryption via the qpdf engine.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "protect",
  },
  "unlock-pdf": {
    slug: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove restrictions with the valid password.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "unlock",
  },
  "sanitize-pdf": {
    slug: "sanitize-pdf",
    title: "Sanitize PDF",
    description: "Scrub metadata, scripts, annotations and forms per toggle.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "sanitize",
  },
  "flatten-pdf": {
    slug: "flatten-pdf",
    title: "Flatten PDF",
    description: "Bake form field values into static page content.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "flatten",
  },
  "remove-metadata": {
    slug: "remove-metadata",
    title: "Remove Metadata",
    description: "Strip Info dictionary, XMP stream and PieceInfo.",
    accepts: [".pdf"],
    acceptMime: ".pdf,application/pdf",
    multiple: false,
    kind: "remove-metadata",
  },
};

export function getToolSpec(slug: string): ToolSpec | null {
  return TIER1_TOOLS[slug] ?? null;
}

// Free-plan queue caps. Larger batches are a premium feature.
export const FREE_QUEUE_LIMIT: Record<string, number> = {
  "merge-pdf": 10,
  "images-to-pdf": 20,
  "jpg-to-pdf": 20,
  "png-to-pdf": 20,
  "webp-to-pdf": 20,
  "compare-pdfs": 2,
};

// Slugs with a catalog card but no engine yet. The tool page renders a
// "Coming soon" panel instead of the uploader for these.
export const COMING_SOON: ReadonlySet<string> = new Set([
  "ocr-pdf",
  "powerpoint-to-pdf",
  "epub-to-pdf",
  "pdf-to-pdfa",
  "digital-signature-pdf",
]);
